version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "2525:3306"
    environment:
      MYSQL_DATABASE: dzenCodeDB
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env
    depends_on:
      - db
    command: >
      sh -c "
        echo 'Waiting for MySQL...' &&
        until nc -z db 3306; do sleep 1; done &&
        echo 'MySQL started!' &&
        python /app/manage.py migrate &&
        gunicorn configs.wsgi:application --bind 0.0.0.0:8000
      "

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  mysql-data:
