# Generated by Django 5.1.7 on 2025-04-08 08:10

import core.services.upload_files_service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_commentsmodel_image_commentsmodel_text_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.services.upload_files_service.upload_picture_to_comment),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to=core.services.upload_files_service.upload_text_file_to_comment),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.services.upload_files_service.upload_picture_to_post),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to=core.services.upload_files_service.upload_text_file_to_post),
        ),
    ]
